CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        description VARCHAR(1000) NOT NULL,
                                        requestor_id BIGINT NOT NULL,
                                        created TIMESTAMP NOT NULL,
                                        CONSTRAINT pk_request PRIMARY KEY (id),
                                        CONSTRAINT fk_request_user FOREIGN KEY (requestor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(1000) NOT NULL,
                                     available BOOLEAN NOT NULL,
                                     owner_id BIGINT NOT NULL,
                                     request_id BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY (id),
                                     CONSTRAINT fk_item_user FOREIGN KEY (owner_id) REFERENCES users(id),
                                     CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS booking (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       item_id BIGINT NOT NULL,
                                       user_id BIGINT NOT NULL,
                                       start_time TIMESTAMP NOT NULL,
                                       end_time TIMESTAMP NOT NULL,
                                       status INT NOT NULL,
                                       CONSTRAINT pk_booking PRIMARY KEY (id),
                                       CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id),
                                       CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        item_id BIGINT NOT NULL,
                                        user_id BIGINT NOT NULL,
                                        text VARCHAR(500) NOT NULL,
                                        created TIMESTAMP NOT NULL,
                                        CONSTRAINT pk_comments PRIMARY KEY (id),
                                        CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items(id),
                                        CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
);